### ISSUE TITLE
Add Input font

### ISSUE THREAD

**Issue by andrewbernard** [braver/fonts#100]
Is there any way to add fonts to the package? The superb Input font appears to be missing, for one.

**Comment by lierdakil** [comment]
Hello! If you're interested in making a pull request, we have a [contributing guide](https://github.com/braver/fonts/blob/master/.github/CONTRIBUTING.md). However, we can't add the Input font because the terms of [its licence](https://input.fontbureau.com/license/) forbid redistribution:

> NO REDISTRIBUTION. You may not distribute the Font Software to third parties for the purposes of permitting the display of the Font Software or allowing or facilitating redistribution of the Font Software irrespective of the terms of the redistribution. For the purposes of clarity you are not permitted to embed the Font Software or otherwise bundle the Font Software with another file. All such uses require the purchase of a special license.

If you just want to use the font personally, it's easy enough to install it on the system level and just tell Atom to use it, or write a couple lines of CSS `@font-face` definition in your Atom stylesheet if you prefer. You don't need the fonts package to use a font, the package is just a convenient way to testdrive multiple fonts to see if you like one.
