### ISSUE TITLE
Indent Guide is misaligned with invisibles turned on for Roboto

### ISSUE THREAD

**Issue by mstewart6** [braver/fonts#79]
Originally from: https://github.com/elixir-editors/language-elixir/issues/108

For Roboto (and all its variants) using Elixir grammar, the guidelines are misaligned when blank lines are adjacent to non-blank ones with invisibles turned on. I believe the carriage return character is just not set to be as wide as the two spaces. On font size 13 the `  `(double blank space) is only 15.266px wide, but the `··` is 15.609px. Also the `¬` is only 7.813px wide for a single character.

This leads me to believe some odd math happening to account for the 1px border for the indent guides, but leading to those invisibles not being monospace themselves. Oddly, I have not seen this issue in other grammars yet, but I suspect it is not just limited to Elixir. Also, the other fonts included in this package seem to be fine, but I have not tried them all.

![image](https://user-images.githubusercontent.com/18093356/46543014-77bed200-c885-11e8-9281-6f7829dd570a.png)

**Comment by lierdakil** [comment]
Certainly, this is the wrong place to create this issue. All this package does is repackage some fonts for your convenience, we're neither authors of the fonts, nor affiliated with Atom core team...

Anywho, this problem arises due to italicized Roboto Mono being a smidge narrower than non-italicized Roboto Mono. This much is self-evident from the [demo page](https://fonts.google.com/specimen/Roboto+Mono)
![The word "regular" rendered using Roboto Mono Regular, non-italicized and italicized](https://user-images.githubusercontent.com/7275622/46560457-83011480-c8fc-11e8-99c2-9654fb38b1b1.png)
If you squint a bit, you can see that italicized version takes up a little bit less horizontal space.
Frankly, this is an issue with the font itself. If you want to complain about that, I'd suggest to take it up with Google, but there is already an issue for that since 2015, and it doesn't seem like there's any movement there https://github.com/google/fonts/issues/142. If somebody can (or already did) patch the font to fix this, get in touch, we'd be happy to include a patched version.

You could mitigate the problem by adding something like this to Atom stylesheet
```css
atom-text-editor .invisible-character {
  font-style: inherit !important;
}
```
The reason this works is Atom core forces invisible characters to `normal` style, and this css snippet overrides that. I don't know why that is, but there probably is a reason. If you think this is an issue and should be fixed, I suggest you take it up with the Atom team. Note that indent guides will *still* be misaligned between italicized and non-italicized text.

You could also go another direction, and force indent-guide text to be *non-*italicized:
```css
atom-text-editor .indent-guide {
  font-style: normal !important;
}
```
That would work, but not quite, since stray spaces do tend to creep into the render, and those *will* be italicized. Again, if you think this is something that needs fixing, I suggest you take it up with the Atom team.

The easiest solution -- just disable italicization:
```css
.syntax--comment {
  font-style: normal;
}
```
(and wherever else it might be used). The downside is, well, you lose italicization.

Or, you know, just pick another font. Thankfully, it's super easy using the fonts package. Inconsolata-g is pretty similar to Roboto Mono, if you want a recommendation.
