### ISSUE TITLE
Feature request: preview field in settings view

### ISSUE THREAD

**Issue by olmokramer** [braver/fonts#8]
An extra item in the config object to show a text field under the select box, to serve as a font preview field, so you don't have to switch to an editor every time you change the font
```coffee
config:
  preview:
    type: 'string'
    description: 'Preview your selected font in this field'
```
for example

**Comment by braver** [comment]
That's actually a pretty good idea, and pretty easy. https://github.com/braver/fonts/commit/bd7cd7e6f77f454329bac11f01017f06e63bc942 should do it.

Two extra bonus tips:
- split panes to have some real code right next to the settings view and watch it change for every font
- use http://app.programmingfonts.org to figure out what font you like best

I'll do some testing and publish an update later today.

**Comment by olmokramer** [comment]
Thanks! Also for the tips :) Personally I never use split panes, so I always forget they exist... I think it's a better solution than a single line preview box because you see <em>actual code</em> in the pane, but at least this is something :)

By the way, any chance you'll be adding the [Fira Code](https://github.com/tonsky/FiraCode) font? Or would that be difficult with font measurements etc.?

**Comment by braver** [comment]
I've considered that. However, Atom doesn't really have support for ligatures. Some other Open Type features should work but since ligatures are Fira Code's main feature that's not going to work. Other than the ligatures it's just Fira Mono, which is already available in this package. 
Same goes for [Hasklig](https://github.com/i-tu/Hasklig). I will add them if Atom solves [the issues around ligatures](https://github.com/atom/atom/issues/3821#issuecomment-74414131).
